# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model:
#    + IONet
#    + descriptor upsampling
#    + cross-border keypoints
#    + descriptor loss
arch:
    epochs: 50
model:
    params:
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
    checkpoint_path: '../../../scratch/rueeggth/kp2d' 

wandb:
    dry_run: True
    project: ""
datasets:
    augmentation:
        mode: 'sonar_sim'
        fov: 60
        r_min: 0.1
        r_max: 5

    train:
        path: '../../../scratch/rueeggth/dataset/SonarDataSets/Simulated'
        num_workers: 16
        batch_size: 4
    val:
        path: "../Dataset/HPatches/hpatches-sequences-release/"


