# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model:
#    + IONet
#    + descriptor upsampling
#    + cross-border keypoints
#    + descriptor loss

model:
    params:
        use_color: False
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
        checkpoint_path: '../../../scratch/kp2d' 

wandb:
    dry_run: True
    project: ""
datasets:
    train:
        path: "../Dataset/SonarDataSets/Simulated/GrateSceneRoundTrip"
        num_workers: 16
    val:
        path: "../Dataset/HPatches/hpatches-sequences-release/
"


