# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model:
#    + IONet
#    + descriptor upsampling
#    + cross-border keypoints
#    + descriptor loss

model:
    params:
        use_color: False
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True

wandb:
    dry_run: True
    project: ""
datasets:
    train:
        path: "D:/MachineLearning/SonarData/SonarDataSets/Simulated/GrateIsolatedFullScan"
    val:
        path: "D:/PycharmProjects/KP2D/data/datasets/kp2d/HPatches"

